oarepo/oarepo-ui

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/CountElement.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppLayout.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppResultOptions.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppResults.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppSearchbarContainer.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppSort.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/index.js, oarepo_ui/theme/assets/semantic-ui/translations/oarepo_ui/messages/cs/translations.json, oarepo_ui/theme/assets/semantic-ui/translations/oarepo_ui/messages/en/translations.json
fixed searchBar and translations
=> fixed searchBar and translations

oarepo_ui/resources/resource.py, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/CountElement.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppLayout.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppResultOptions.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppResults.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppSearchbarContainer.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppSort.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/index.js, oarepo_ui/theme/assets/semantic-ui/translations/oarepo_ui/messages/cs/translations.json, oarepo_ui/theme/assets/semantic-ui/translations/oarepo_ui/messages/en/translations.json, setup.cfg
Added extra context to detail and search views
Fixes #33
=> Add extra context

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/CountElement.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/EmptyResultsElement.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppResultOptions.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/index.js, oarepo_ui/theme/assets/semantic-ui/translations/oarepo_ui/messages/cs/translations.json, oarepo_ui/theme/assets/semantic-ui/translations/oarepo_ui/messages/en/translations.json
modified countelement addedd EmptyResultsElement
sorry for the bad branch name, I kept working on the branch we had previously.
=> modified countelement addedd EmptyResultsElement

oarepo_ui/resources/__init__.py, oarepo_ui/resources/config.py, oarepo_ui/resources/resource.py, oarepo_ui/utils.py, setup.cfg, tests/conftest.py, tests/test_templating.py, tests/test_ui_resource.py
* does not output files if files are not configured on the record
* RecordUIResourceConfig  contains empty_record property for easier (out-of-code) customization
=> service.new_record handles props correctly

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/hooks.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/util.js, setup.cfg
@mirekys Ahoj Miro, I fixed this issue by simply passing default onBeforeSubmit func that takes value and returns it. I tried it out and it works fine. It seems that we have different prettifier or something that is marking all lines in the codes as changed, so we should probably consider sitting down and making uniform settings between all of us who work on FE, to reduce the clutter and make PRs easier to check.
=> fixed issue with onbeforesubmit

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/MultilingualTextInput/MultilingualTextInput.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/util.js
Moved function that prevents choosing same languages in multilingual input to oarepo-ui utils
=> moved eliminateLangFunc to utils

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/MultilingualTextInput/MultilingualTextInput.jsx, setup.cfg
@mirekys I removed the unused prop and also made some small modification that I noticed earlier was missing in the component (the add button label was hardcoded and not passed as a prop).
=> removed unused prop

oarepo_ui/config.py, oarepo_ui/resources/resource.py, oarepo_ui/templates/oarepo_ui/header.html, oarepo_ui/templates/oarepo_ui/header_login.html, setup.cfg
From now on, authentication will be required on create & edit forms by default
=> feat(auth): :passport_control: enable local account authn & authz

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/ArrayFieldItem/ArrayFieldItem.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/ArrayFieldItem/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/I18nRichInputField/I18nRichInputField.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/I18nTextInputField/I18nTextInputField.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/MultilingualTextInput/MultilingualTextInput.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/hooks.js, setup.cfg
@mirekys Zdar, here is what we discussed today. There are no big changes, a few props and hover state possibility (when you hover the close button to highlight the inputs you will remove). Please take a look.
=> added hoverstate and few props

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/RelatedSelectField/RelatedSelectFieldInternal.jsx, setup.cfg
initialize suggestions from value, if present (fixes display when editing existing value)
=> Fix initial suggestions in RelatedSelectField

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/ConfirmationModal/ConfirmationModal.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/ConfirmationModal/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/DeleteButton/DeleteButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/DeleteButton/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/FormikStateLogger/FormikStateLogger.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/PreviewButton/PreviewButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/PreviewButton/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/PublishButton/PublishButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/PublishButton/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/SaveButton/SaveButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/SaveButton/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/ValidateButton/ValidateButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/ValidateButton/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/index.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/hooks.js, oarepo_ui/theme/assets/semantic-ui/translations/oarepo_ui/messages/cs/LC_MESSAGES/translations.json, setup.cfg
This refactors & migrates generic form buttons as implemented in nr-docs, to be reused in many other repositories
=> feat(forms): refactor button components from nr-docs

oarepo_ui/templates/oarepo_ui/base_page.html, oarepo_ui/templates/oarepo_ui/css.html, oarepo_ui/templates/oarepo_ui/javascript.html, setup.cfg
added base_page and css template
=> added extensible css block

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppLayout.jsx, setup.cfg
Made restructuring of search app layout, so that searchbar is not rerendered when the facet sidebar opens, and in that way it does not disappear from the UI. Link to linear https://linear.app/ducesnet/issue/EP-99/search-bar-bug
=> fixed search bar disappearing bug

oarepo_ui/resources/__init__.py, oarepo_ui/resources/components/__init__.py, oarepo_ui/resources/components/babel.py, oarepo_ui/resources/components/base.py, oarepo_ui/resources/components/bleach.py, oarepo_ui/resources/components/communities.py, oarepo_ui/resources/components/files.py, oarepo_ui/resources/components/permissions.py, setup.cfg, tests/model.py
Adds `allowed_communities` to form_config during `create` operation.
=> Added AllowedCommunitiesComponent

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/EDTFDatePickerField/utils.js, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchappSearchbarElement.jsx
Datum zveřejnění - pokud si vyberu, že chci zadat jen rok a potvrdím rok, vyhodí mě to ze záznamu a ten nikde nezůstane rozpracovaný, nedá se k němu vrátit - bug with single date picker
=> fixed bug with selecting just year in single picker

oarepo_ui/resources/components/permissions.py, oarepo_ui/resources/resource.py, setup.cfg
to check if user has right to deposit a record and show UI button on search page
=> Using "view_deposit_page" permission instead of "create" permission

oarepo_ui/resources/resource.py, setup.cfg
@mirekys Setting dangerous innerhtml on search items (related PR https://github.com/Narodni-repozitar/nr-docs/pull/190)
=> added allowed html tags to search config

oarepo_ui/resources/components/__init__.py, oarepo_ui/resources/components/files_locked.py, oarepo_ui/resources/resource.py, setup.cfg
Minor modifications to obtain, in form config same boolean values as RDM uses for edit/create routes.
=> added files locked to form config, mimicking how its done in invenio

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/BaseFormLayout/BaseFormLayout.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/FilesField/FilesField.jsx, setup.cfg
cleanup after moving components. Related PRS
https://github.com/Narodni-repozitar/nr-model/pull/98
https://github.com/Narodni-repozitar/nr-docs/pull/262
=> passing prop to the files table

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/util.js
Made a small optimization on the output recieved by useFieldData hook. I tested with profiler and it works better now i.e. the components don't seem to rerender due to data recieved from the hook. While making this, I had a weird issue with circular imports, after which I checked the import graph and it is a real big mess. However, I don't know if it makes sense to go into refactoring at this point as I am not sure when we plan to start using that monorepo you prepared (design system).
=> memoized getfield data output

oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/NestedErrors/NestedErrors.jsx, setup.cfg
=> fixed nested errors

oarepo_ui/resources/config.py, oarepo_ui/resources/resource.py, oarepo_ui/templates/oarepo_ui/base_page.html, oarepo_ui/templates/oarepo_ui/detail.html, setup.cfg
=> passing embedded param from BE

oarepo_ui/resources/config.py, oarepo_ui/resources/resource.py, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/ActiveFiltersElement.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/ClearFiltersButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/SearchAppLayout.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/ShouldActiveFiltersRender.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/search/hooks.js, setup.cfg, tests/test_ui_resource.py
*if someone clicks on search link and that facet is not in aggs in search config it will not be handler properly in UI
=> feature: sending additional facet labes to search config

oarepo_ui/templates/components/RecordSharing.jinja
Related PR: https://github.com/Narodni-repozitar/nr-docs/pull/375
=> fix(template): close div tag in RecordSharing component to prevent React bugs

oarepo_ui/theme/webpack.py
*additionally removed conditional dependencies for v11
=> fix: added dep to react-query which was previously in vocabularies

oarepo_ui/resources/components/__init__.py, oarepo_ui/resources/components/files.py, oarepo_ui/resources/components/files_quota.py, oarepo_ui/resources/records/config.py, oarepo_ui/resources/records/resource.py, oarepo_ui/templates/components/SidebarLink.jinja, oarepo_ui/templates/components/datafields/ITableField.jinja, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/DeleteButton/DeleteButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/FormFeedback/FormFeedback.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/PreviewButton/PreviewButton.jsx, oarepo_ui/theme/assets/semantic-ui/js/oarepo_ui/forms/components/SaveButton/SaveButton.jsx, tests/model.py, tests/test_create.py
Needs https://github.com/oarepo/oarepo-runtime/pull/339
=> Rdm 13 testing sample repo
